2026-04-18 19:52:00.583 [error] TypeError: Cannot read properties of null (reading 'useState')
    at exports.useState (/var/task/node_modules/react/cjs/react.production.min.js:26:234)
    at I (/var/task/.next/server/pages/api/claude.js:1:42431)
    at K (/var/task/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16859)
    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
    at async U.render (/var/task/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)
    at async r3.runApi (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:43997)
    at async r3.handleCatchallRenderRequest (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:37953)
    at async r3.runImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:17465)
    at async r3.handleRequestImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:16554)
    at async Object.handler (/var/task/___next_launcher.cjs:57:3)
2026-04-18 19:52:00.583 [error] ⨯ TypeError: Cannot read properties of null (reading 'useState')
    at exports.useState (/var/task/node_modules/react/cjs/react.production.min.js:26:234)
    at I (/var/task/.next/server/pages/api/claude.js:1:42431)
    at K (/var/task/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16859)
    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
    at async U.render (/var/task/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)
    at async r3.runApi (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:43997)
    at async r3.handleCatchallRenderRequest (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:37953)
    at async r3.runImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:17465)
    at async r3.handleRequestImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:16554)
    at async Object.handler (/var/task/___next_launcher.cjs:57:3)
2026-04-18 19:52:00.588 [error] TypeError: Cannot read properties of null (reading 'useState')
    at exports.useState (/var/task/node_modules/react/cjs/react.production.min.js:26:234)
    at I (/var/task/.next/server/pages/api/claude.js:1:42431)
    at K (/var/task/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16859)
    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
    at async U.render (/var/task/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)
    at async r3.runApi (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:43997)
    at async r3.handleCatchallRenderRequest (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:37953)
    at async r3.runImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:17465)
    at async r3.handleRequestImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:16554)
    at async Object.handler (/var/task/___next_launcher.cjs:57:3)
